# Taxonomy mapping definitions used by canopy.

TAXON_PLURALS = {
    'kingdom': 'kingdoms',
    'subkingdom': 'subkingdoms',
    'phylum': 'phyla',
    'subphylum': 'subphyla',
    'class': 'classes',
    'subclass': 'subclasses',
    'order': 'orders',
    'suborder': 'suborders',
    'family': 'families',
    'subfamily': 'subfamilies',
    'tribe': 'tribes',
    'subtribe': 'subtribes',
    'genus': 'genera',
    'subgenus': 'subgenera',
    'section': 'sections',
    'subsection': 'subsections',
    'series': 'series', 			# "series" is both singular and plural
    'subseries': 'subseries', 		# "subseries" is both singular and plural
    'species': 'species', 			# "species" is both singular and plural
    'grex': 'grexes',
    'subspecies': 'subspecies',		# "subspecies" is both singular and plural
    'variety': 'varieties',
    'subvariety': 'subvarieties',
    'form': 'forms',
    'subform': 'subforms',
    'lusus': 'lusus', 				# rarely used, typically remains unchanged
    'cultivar': 'cultivars',
    'complex': 'complexes',
    'unranked': 'unranked' 			# typically remains unchanged
}

TAXON_ABBREVIATIONS = {
    "GREX": "gx.",
    "SUBSPECIES": "ssp.",  	
    "VARIETY": "var.",
    "SUBVARIETY": "subvar.",
    "FORM": "f.",
    "SUBFORM": "subf.",
    "LUSUS": "lus.",
    "CULTIVAR": "cv.",       		# Often shown with single quotes instead
    "COMPLEX": "",    				# Usually not abbreviated
    "UNRANKED": ""           		# No standard abbreviation
}


WGSRPDLOOKUP = {
	# L1
	1: {'name': 'Europe', 'level': 1},
	2: {'name': 'Africa', 'level': 1},
	3: {'name': 'Northern Asia', 'level': 1},
	4: {'name': 'Tropical Asia', 'level': 1},
	5: {'name': 'Australasia', 'level': 1},
	6: {'name': 'Pacific', 'level': 1},
	7: {'name': 'North America', 'level': 1},
	8: {'name': 'South America', 'level': 1},
	9: {'name': 'Antarctic', 'level': 1},
	# L2
	10: {'name': 'Northern Europe', 'parent': 1, 'level': 2},
	11: {'name': 'Central Europe', 'parent': 1, 'level': 2},
	12: {'name': 'Southwestern Europe', 'parent': 1, 'level': 2},
	13: {'name': 'Southeastern Europe', 'parent': 1, 'level': 2},
	14: {'name': 'Eastern Europe', 'parent': 1, 'level': 2},
	20: {'name': 'Northern Africa', 'parent': 2, 'level': 2},
	21: {'name': 'Atlantic Islands', 'parent': 2, 'level': 2},
	22: {'name': 'Western Africa', 'parent': 2, 'level': 2},
	23: {'name': 'West-Central Africa', 'parent': 2, 'level': 2},
	24: {'name': 'Northeast Tropical Africa', 'parent': 2, 'level': 2},
	25: {'name': 'East Tropical Africa', 'parent': 2, 'level': 2},
	26: {'name': 'South Tropical Africa', 'parent': 2, 'level': 2},
	27: {'name': 'Southern Africa', 'parent': 2, 'level': 2},
	28: {'name': 'Middle Atlantic Ocean', 'parent': 2, 'level': 2},
	29: {'name': 'Western Indian Ocean', 'parent': 2, 'level': 2},
	30: {'name': 'Siberia', 'parent': 3, 'level': 2},
	31: {'name': 'Russian Far East', 'parent': 3, 'level': 2},
	32: {'name': 'Central Asia', 'parent': 3, 'level': 2},
	33: {'name': 'Caucasus', 'parent': 3, 'level': 2},
	34: {'name': 'Western Asia', 'parent': 3, 'level': 2},
	35: {'name': 'Arabian Peninsula', 'parent': 3, 'level': 2},
	36: {'name': 'China', 'parent': 3, 'level': 2},
	37: {'name': 'Mongolia', 'parent': 3, 'level': 2},
	38: {'name': 'Eastern Asia', 'parent': 3, 'level': 2},
	40: {'name': 'Indian Subcontinent', 'parent': 4, 'level': 2},
	41: {'name': 'Southeast Asia', 'parent': 4, 'level': 2},
	42: {'name': 'Malesia', 'parent': 4, 'level': 2},
	43: {'name': 'New Guinea', 'parent': 4, 'level': 2},
	50: {'name': 'Australia', 'parent': 5, 'level': 2},
	51: {'name': 'New Zealand', 'parent': 5, 'level': 2},
	60: {'name': 'Southwestern Pacific', 'parent': 6, 'level': 2},
	61: {'name': 'South-Central Pacific', 'parent': 6, 'level': 2},
	62: {'name': 'Northwestern Pacific', 'parent': 6, 'level': 2},
	63: {'name': 'North-Central Pacific', 'parent': 6, 'level': 2},
	70: {'name': 'Subarctic America', 'parent': 7, 'level': 2},
	71: {'name': 'Western Canada', 'parent': 7, 'level': 2},
	72: {'name': 'Eastern Canada', 'parent': 7, 'level': 2},
	73: {'name': 'Northwestern U.S.', 'parent': 7, 'level': 2},
	74: {'name': 'Northern U.S.', 'parent': 7, 'level': 2},
	75: {'name': 'Northeastern U.S.', 'parent': 7, 'level': 2},
	76: {'name': 'Southwestern U.S.', 'parent': 7, 'level': 2},
	77: {'name': 'Southern U.S.', 'parent': 7, 'level': 2},
	78: {'name': 'Southeastern U.S.', 'parent': 7, 'level': 2},
	79: {'name': 'Mexico', 'parent': 7, 'level': 2},
	80: {'name': 'Central America', 'parent': 8, 'level': 2},
	81: {'name': 'Caribbean', 'parent': 8, 'level': 2},
	82: {'name': 'Northern South America', 'parent': 8, 'level': 2},
	83: {'name': 'Western South America', 'parent': 8, 'level': 2},
	84: {'name': 'Brazil', 'parent': 8, 'level': 2},
	85: {'name': 'Southern South America', 'parent': 8, 'level': 2},
	90: {'name': 'Subantarctic Islands', 'parent': 9, 'level': 2},
	91: {'name': 'Antarctica', 'parent': 9, 'level': 2},
	# L3
	'ABT': {'name': 'Alberta', 'parent': 71, 'level': 3},
	'AFG': {'name': 'Afghanistan', 'parent': 34, 'level': 3},
	'AGE': {'name': 'Argentinian Northeast', 'parent': 85, 'level': 3},
	'AGS': {'name': 'Argentinian South', 'parent': 85, 'level': 3},
	'AGW': {'name': 'Argentinian Northwest', 'parent': 85, 'level': 3},
	'ALA': {'name': 'Alabama', 'parent': 78, 'level': 3},
	'ALB': {'name': 'Albania', 'parent': 13, 'level': 3},
	'ALD': {'name': 'Aldabra', 'parent': 29, 'level': 3},
	'ALG': {'name': 'Algeria', 'parent': 20, 'level': 3},
	'ALT': {'name': 'Altay', 'parent': 30, 'level': 3},
	'ALU': {'name': 'Aleutian Islands', 'parent': 70, 'level': 3},
	'AMU': {'name': 'Amur', 'parent': 31, 'level': 3},
	'AND': {'name': 'Andaman Islands', 'parent': 41, 'level': 3},
	'ANG': {'name': 'Angola', 'parent': 26, 'level': 3},
	'ANT': {'name': 'Antarctica', 'parent': 91, 'level': 3},
	'ARI': {'name': 'Arizona', 'parent': 76, 'level': 3},
	'ARK': {'name': 'Arkansas', 'parent': 78, 'level': 3},
	'ARU': {'name': 'Aruba', 'parent': 81, 'level': 3},
	'ASC': {'name': 'Ascension', 'parent': 28, 'level': 3},
	'ASK': {'name': 'Alaska', 'parent': 70, 'level': 3},
	'ASP': {'name': 'Amsterdam-St.Paul Islands', 'parent': 90, 'level': 3},
	'ASS': {'name': 'Assam', 'parent': 40, 'level': 3},
	'ATP': {'name': 'Antipodean Islands', 'parent': 51, 'level': 3},
	'AUT': {'name': 'Austria', 'parent': 11, 'level': 3},
	'AZO': {'name': 'Azores', 'parent': 21, 'level': 3},
	'BAH': {'name': 'Bahamas', 'parent': 81, 'level': 3},
	'BAL': {'name': 'Baleares', 'parent': 12, 'level': 3},
	'BAN': {'name': 'Bangladesh', 'parent': 40, 'level': 3},
	'BEN': {'name': 'Benin', 'parent': 22, 'level': 3},
	'BER': {'name': 'Bermuda', 'parent': 81, 'level': 3},
	'BGM': {'name': 'Belgium', 'parent': 11, 'level': 3},
	'BIS': {'name': 'Bismarck Archipelago', 'parent': 43, 'level': 3},
	'BKN': {'name': 'Burkina', 'parent': 22, 'level': 3},
	'BLR': {'name': 'Belarus', 'parent': 14, 'level': 3},
	'BLT': {'name': 'Baltic States', 'parent': 14, 'level': 3},
	'BLZ': {'name': 'Belize', 'parent': 80, 'level': 3},
	'BOL': {'name': 'Bolivia', 'parent': 83, 'level': 3},
	'BOR': {'name': 'Borneo', 'parent': 42, 'level': 3},
	'BOT': {'name': 'Botswana', 'parent': 27, 'level': 3},
	'BOU': {'name': 'Bouvet Island', 'parent': 90, 'level': 3},
	'BRC': {'name': 'British Columbia', 'parent': 71, 'level': 3},
	'BRY': {'name': 'Buryatiya', 'parent': 30, 'level': 3},
	'BUL': {'name': 'Bulgaria', 'parent': 13, 'level': 3},
	'BUR': {'name': 'Burundi', 'parent': 23, 'level': 3},
	'BZC': {'name': 'West-Central Brazil', 'parent': 84, 'level': 3},
	'BZE': {'name': 'Northeast Brazil', 'parent': 84, 'level': 3},
	'BZL': {'name': 'Southeast Brazil', 'parent': 84, 'level': 3},
	'BZN': {'name': 'North Brazil', 'parent': 84, 'level': 3},
	'BZS': {'name': 'South Brazil', 'parent': 84, 'level': 3},
	'CAB': {'name': 'Cabinda', 'parent': 23, 'level': 3},
	'CAF': {'name': 'Central African Republic', 'parent': 23, 'level': 3},
	'CAL': {'name': 'California', 'parent': 76, 'level': 3},
	'CAY': {'name': 'Cayman Islands', 'parent': 81, 'level': 3},
	'CBD': {'name': 'Cambodia', 'parent': 41, 'level': 3},
	'CGS': {'name': 'Chagos Archipelago', 'parent': 29, 'level': 3},
	'CHA': {'name': 'Chad', 'parent': 24, 'level': 3},
	'CHC': {'name': 'China South-Central', 'parent': 36, 'level': 3},
	'CHH': {'name': 'Hainan', 'parent': 36, 'level': 3},
	'CHI': {'name': 'Inner Mongolia', 'parent': 36, 'level': 3},
	'CHM': {'name': 'Manchuria', 'parent': 36, 'level': 3},
	'CHN': {'name': 'China North-Central', 'parent': 36, 'level': 3},
	'CHQ': {'name': 'Qinghai', 'parent': 36, 'level': 3},
	'CHS': {'name': 'China Southeast', 'parent': 36, 'level': 3},
	'CHT': {'name': 'Tibet', 'parent': 36, 'level': 3},
	'CHX': {'name': 'Xinjiang', 'parent': 36, 'level': 3},
	'CKI': {'name': 'Cocos (Keeling) Islands', 'parent': 42, 'level': 3},
	'CLC': {'name': 'Chile Central', 'parent': 85, 'level': 3},
	'CLM': {'name': 'Colombia', 'parent': 83, 'level': 3},
	'CLN': {'name': 'Chile North', 'parent': 85, 'level': 3},
	'CLS': {'name': 'Chile South', 'parent': 85, 'level': 3},
	'CMN': {'name': 'Cameroon', 'parent': 23, 'level': 3},
	'CNT': {'name': 'Connecticut', 'parent': 75, 'level': 3},
	'CNY': {'name': 'Canary Islands', 'parent': 21, 'level': 3},
	'COL': {'name': 'Colorado', 'parent': 73, 'level': 3},
	'COM': {'name': 'Comoros', 'parent': 29, 'level': 3},
	'CON': {'name': 'Congo', 'parent': 23, 'level': 3},
	'COO': {'name': 'Cook Islands', 'parent': 61, 'level': 3},
	'COR': {'name': 'Corse', 'parent': 12, 'level': 3},
	'COS': {'name': 'Costa Rica', 'parent': 80, 'level': 3},
	'CPI': {'name': 'Central American Pacific Islands', 'parent': 80, 'level': 3},
	'CPP': {'name': 'Cape Provinces', 'parent': 27, 'level': 3},
	'CPV': {'name': 'Caprivi Strip', 'parent': 27, 'level': 3},
	'CRL': {'name': 'Caroline Islands', 'parent': 62, 'level': 3},
	'CRZ': {'name': 'Crozet Islands', 'parent': 90, 'level': 3},
	'CTA': {'name': 'Chita', 'parent': 30, 'level': 3},
	'CTM': {'name': 'Chatham Islands', 'parent': 51, 'level': 3},
	'CUB': {'name': 'Cuba', 'parent': 81, 'level': 3},
	'CVI': {'name': 'Cape Verde', 'parent': 21, 'level': 3},
	'CYP': {'name': 'Cyprus', 'parent': 34, 'level': 3},
	'CZE': {'name': 'Czech Republic', 'parent': 11, 'level': 3},
	'DEL': {'name': 'Delaware', 'parent': 78, 'level': 3},
	'DEN': {'name': 'Denmark', 'parent': 10, 'level': 3},
	'DJI': {'name': 'Djibouti', 'parent': 24, 'level': 3},
	'DOM': {'name': 'Dominican Republic', 'parent': 81, 'level': 3},
	'DSV': {'name': 'Desventurados Islands', 'parent': 85, 'level': 3},
	'EAI': {'name': 'East Aegean Islands', 'parent': 34, 'level': 3},
	'EAS': {'name': 'Easter Island', 'parent': 61, 'level': 3},
	'ECU': {'name': 'Ecuador', 'parent': 83, 'level': 3},
	'EGY': {'name': 'Egypt', 'parent': 20, 'level': 3},
	'EHM': {'name': 'East Himalaya', 'parent': 40, 'level': 3},
	'ELS': {'name': 'El Salvador', 'parent': 80, 'level': 3},
	'EQG': {'name': 'Equatorial Guinea', 'parent': 23, 'level': 3},
	'ERI': {'name': 'Eritrea', 'parent': 24, 'level': 3},
	'ETH': {'name': 'Ethiopia', 'parent': 24, 'level': 3},
	'FAL': {'name': 'Falkland Islands', 'parent': 90, 'level': 3},
	'FIJ': {'name': 'Fiji', 'parent': 60, 'level': 3},
	'FIN': {'name': 'Finland', 'parent': 10, 'level': 3},
	'FLA': {'name': 'Florida', 'parent': 78, 'level': 3},
	'FOR': {'name': 'Faroe Islands', 'parent': 10, 'level': 3},
	'FRA': {'name': 'France', 'parent': 12, 'level': 3},
	'FRG': {'name': 'French Guiana', 'parent': 82, 'level': 3},
	'GAB': {'name': 'Gabon', 'parent': 23, 'level': 3},
	'GAL': {'name': 'Galápagos', 'parent': 83, 'level': 3},
	'GAM': {'name': 'Gambia, The', 'parent': 22, 'level': 3},
	'GEO': {'name': 'Georgia', 'parent': 78, 'level': 3},
	'GER': {'name': 'Germany', 'parent': 11, 'level': 3},
	'GGI': {'name': 'Gulf of Guinea Islands', 'parent': 23, 'level': 3},
	'GHA': {'name': 'Ghana', 'parent': 22, 'level': 3},
	'GIL': {'name': 'Gilbert Islands', 'parent': 60, 'level': 3},
	'GNB': {'name': 'Guinea-Bissau', 'parent': 22, 'level': 3},
	'GNL': {'name': 'Greenland', 'parent': 70, 'level': 3},
	'GRB': {'name': 'Great Britain', 'parent': 10, 'level': 3},
	'GRC': {'name': 'Greece', 'parent': 13, 'level': 3},
	'GST': {'name': 'Gulf States', 'parent': 35, 'level': 3},
	'GUA': {'name': 'Guatemala', 'parent': 80, 'level': 3},
	'GUI': {'name': 'Guinea', 'parent': 22, 'level': 3},
	'GUY': {'name': 'Guyana', 'parent': 82, 'level': 3},
	'HAI': {'name': 'Haiti', 'parent': 81, 'level': 3},
	'HAW': {'name': 'Hawaii', 'parent': 63, 'level': 3},
	'HBI': {'name': 'Howland-Baker Islands', 'parent': 60, 'level': 3},
	'HMD': {'name': 'Heard-McDonald Islands', 'parent': 90, 'level': 3},
	'HON': {'name': 'Honduras', 'parent': 80, 'level': 3},
	'HUN': {'name': 'Hungary', 'parent': 11, 'level': 3},
	'ICE': {'name': 'Iceland', 'parent': 10, 'level': 3},
	'IDA': {'name': 'Idaho', 'parent': 73, 'level': 3},
	'ILL': {'name': 'Illinois', 'parent': 74, 'level': 3},
	'IND': {'name': 'India', 'parent': 40, 'level': 3},
	'INI': {'name': 'Indiana', 'parent': 75, 'level': 3},
	'IOW': {'name': 'Iowa', 'parent': 74, 'level': 3},
	'IRE': {'name': 'Ireland', 'parent': 10, 'level': 3},
	'IRK': {'name': 'Irkutsk', 'parent': 30, 'level': 3},
	'IRN': {'name': 'Iran', 'parent': 34, 'level': 3},
	'IRQ': {'name': 'Iraq', 'parent': 34, 'level': 3},
	'ITA': {'name': 'Italy', 'parent': 13, 'level': 3},
	'IVO': {'name': 'Côte d\'Ivoire', 'parent': 22, 'level': 3},
	'JAM': {'name': 'Jamaica', 'parent': 81, 'level': 3},
	'JAP': {'name': 'Japan', 'parent': 38, 'level': 3},
	'JAW': {'name': 'Java', 'parent': 42, 'level': 3},
	'JNF': {'name': 'Juan Fernández Islands', 'parent': 85, 'level': 3},
	'KAM': {'name': 'Kamchatka', 'parent': 31, 'level': 3},
	'KAN': {'name': 'Kansas', 'parent': 74, 'level': 3},
	'KAZ': {'name': 'Kazakhstan', 'parent': 32, 'level': 3},
	'KEG': {'name': 'Kerguelen', 'parent': 90, 'level': 3},
	'KEN': {'name': 'Kenya', 'parent': 25, 'level': 3},
	'KER': {'name': 'Kermadec Islands', 'parent': 51, 'level': 3},
	'KGZ': {'name': 'Kirgizistan', 'parent': 32, 'level': 3},
	'KHA': {'name': 'Khabarovsk', 'parent': 31, 'level': 3},
	'KOR': {'name': 'Korea', 'parent': 38, 'level': 3},
	'KRA': {'name': 'Krasnoyarsk', 'parent': 30, 'level': 3},
	'KRI': {'name': 'Kriti', 'parent': 13, 'level': 3},
	'KRY': {'name': 'Krym', 'parent': 14, 'level': 3},
	'KTY': {'name': 'Kentucky', 'parent': 78, 'level': 3},
	'KUR': {'name': 'Kuril Islands', 'parent': 31, 'level': 3},
	'KUW': {'name': 'Kuwait', 'parent': 35, 'level': 3},
	'KZN': {'name': 'Kazan-retto', 'parent': 38, 'level': 3},
	'LAB': {'name': 'Labrador', 'parent': 72, 'level': 3},
	'LAO': {'name': 'Laos', 'parent': 41, 'level': 3},
	'LBR': {'name': 'Liberia', 'parent': 22, 'level': 3},
	'LBS': {'name': 'Lebanon-Syria', 'parent': 34, 'level': 3},
	'LBY': {'name': 'Libya', 'parent': 20, 'level': 3},
	'LDV': {'name': 'Laccadive Islands', 'parent': 40, 'level': 3},
	'LEE': {'name': 'Leeward Islands', 'parent': 81, 'level': 3},
	'LES': {'name': 'Lesotho', 'parent': 27, 'level': 3},
	'LIN': {'name': 'Line Islands', 'parent': 61, 'level': 3},
	'LOU': {'name': 'Louisiana', 'parent': 78, 'level': 3},
	'LSI': {'name': 'Lesser Sunda Islands', 'parent': 42, 'level': 3},
	'MAG': {'name': 'Magadan', 'parent': 31, 'level': 3},
	'MAI': {'name': 'Maine', 'parent': 75, 'level': 3},
	'MAN': {'name': 'Manitoba', 'parent': 71, 'level': 3},
	'MAQ': {'name': 'Macquarie Island', 'parent': 90, 'level': 3},
	'MAS': {'name': 'Massachusetts', 'parent': 75, 'level': 3},
	'MAU': {'name': 'Mauritius', 'parent': 29, 'level': 3},
	'MCI': {'name': 'Mozambique Channel Islands', 'parent': 29, 'level': 3},
	'MCS': {'name': 'Marcus Island', 'parent': 62, 'level': 3},
	'MDG': {'name': 'Madagascar', 'parent': 29, 'level': 3},
	'MDR': {'name': 'Madeira', 'parent': 21, 'level': 3},
	'MDV': {'name': 'Maldives', 'parent': 40, 'level': 3},
	'MIC': {'name': 'Michigan', 'parent': 75, 'level': 3},
	'MIN': {'name': 'Minnesota', 'parent': 74, 'level': 3},
	'MLI': {'name': 'Mali', 'parent': 22, 'level': 3},
	'MLW': {'name': 'Malawi', 'parent': 26, 'level': 3},
	'MLY': {'name': 'Malaya', 'parent': 42, 'level': 3},
	'MNT': {'name': 'Montana', 'parent': 73, 'level': 3},
	'MOL': {'name': 'Maluku', 'parent': 42, 'level': 3},
	'MON': {'name': 'Mongolia', 'parent': 37, 'level': 3},
	'MOR': {'name': 'Morocco', 'parent': 20, 'level': 3},
	'MOZ': {'name': 'Mozambique', 'parent': 26, 'level': 3},
	'MPE': {'name': 'Marion-Prince Edward Islands', 'parent': 90, 'level': 3},
	'MRN': {'name': 'Marianas', 'parent': 62, 'level': 3},
	'MRQ': {'name': 'Marquesas', 'parent': 61, 'level': 3},
	'MRS': {'name': 'Marshall Islands', 'parent': 62, 'level': 3},
	'MRY': {'name': 'Maryland', 'parent': 78, 'level': 3},
	'MSI': {'name': 'Mississippi', 'parent': 78, 'level': 3},
	'MSO': {'name': 'Missouri', 'parent': 74, 'level': 3},
	'MTN': {'name': 'Mauritania', 'parent': 22, 'level': 3},
	'MXC': {'name': 'Mexico Central', 'parent': 79, 'level': 3},
	'MXE': {'name': 'Northeast Mexico', 'parent': 79, 'level': 3},
	'MXG': {'name': 'Mexico Gulf', 'parent': 79, 'level': 3},
	'MXI': {'name': 'Mexican Pacific Islands', 'parent': 79, 'level': 3},
	'MXN': {'name': 'Northwest Mexico', 'parent': 79, 'level': 3},
	'MXS': {'name': 'Southwest Mexico', 'parent': 79, 'level': 3},
	'MXT': {'name': 'Southeast Mexico', 'parent': 79, 'level': 3},
	'MYA': {'name': 'Myanmar', 'parent': 41, 'level': 3},
	'NAM': {'name': 'Namibia', 'parent': 27, 'level': 3},
	'NAT': {'name': 'KwaZulu-Natal', 'parent': 27, 'level': 3},
	'NBR': {'name': 'New Brunswick', 'parent': 72, 'level': 3},
	'NCA': {'name': 'North Carolina', 'parent': 78, 'level': 3},
	'NCB': {'name': 'Nicobar Islands', 'parent': 41, 'level': 3},
	'NCS': {'name': 'North Caucasus', 'parent': 33, 'level': 3},
	'NDA': {'name': 'North Dakota', 'parent': 74, 'level': 3},
	'NEB': {'name': 'Nebraska', 'parent': 74, 'level': 3},
	'NEP': {'name': 'Nepal', 'parent': 40, 'level': 3},
	'NET': {'name': 'Netherlands', 'parent': 11, 'level': 3},
	'NEV': {'name': 'Nevada', 'parent': 76, 'level': 3},
	'NFK': {'name': 'Norfolk Island', 'parent': 50, 'level': 3},
	'NFL': {'name': 'Newfoundland', 'parent': 72, 'level': 3},
	'NGA': {'name': 'Nigeria', 'parent': 22, 'level': 3},
	'NGR': {'name': 'Niger', 'parent': 22, 'level': 3},
	'NIC': {'name': 'Nicaragua', 'parent': 80, 'level': 3},
	'NLA': {'name': 'BES Islands', 'parent': 81, 'level': 3},
	'NNS': {'name': 'Nansei-shoto', 'parent': 38, 'level': 3},
	'NOR': {'name': 'Norway', 'parent': 10, 'level': 3},
	'NRU': {'name': 'Nauru', 'parent': 60, 'level': 3},
	'NSC': {'name': 'Nova Scotia', 'parent': 72, 'level': 3},
	'NSW': {'name': 'New South Wales', 'parent': 50, 'level': 3},
	'NTA': {'name': 'Northern Territory', 'parent': 50, 'level': 3},
	'NUE': {'name': 'Niue', 'parent': 60, 'level': 3},
	'NUN': {'name': 'Nunavut', 'parent': 70, 'level': 3},
	'NWC': {'name': 'New Caledonia', 'parent': 60, 'level': 3},
	'NWG': {'name': 'New Guinea', 'parent': 43, 'level': 3},
	'NWH': {'name': 'New Hampshire', 'parent': 75, 'level': 3},
	'NWJ': {'name': 'New Jersey', 'parent': 75, 'level': 3},
	'NWM': {'name': 'New Mexico', 'parent': 77, 'level': 3},
	'NWT': {'name': 'Northwest Territories', 'parent': 70, 'level': 3},
	'NWY': {'name': 'New York', 'parent': 75, 'level': 3},
	'NZN': {'name': 'New Zealand North', 'parent': 51, 'level': 3},
	'NZS': {'name': 'New Zealand South', 'parent': 51, 'level': 3},
	'OFS': {'name': 'Free State', 'parent': 27, 'level': 3},
	'OGA': {'name': 'Ogasawara-shoto', 'parent': 38, 'level': 3},
	'OHI': {'name': 'Ohio', 'parent': 75, 'level': 3},
	'OKL': {'name': 'Oklahoma', 'parent': 74, 'level': 3},
	'OMA': {'name': 'Oman', 'parent': 35, 'level': 3},
	'ONT': {'name': 'Ontario', 'parent': 72, 'level': 3},
	'ORE': {'name': 'Oregon', 'parent': 73, 'level': 3},
	'PAK': {'name': 'Pakistan', 'parent': 40, 'level': 3},
	'PAL': {'name': 'Palestine', 'parent': 34, 'level': 3},
	'PAN': {'name': 'Panamá', 'parent': 80, 'level': 3},
	'PAR': {'name': 'Paraguay', 'parent': 85, 'level': 3},
	'PEI': {'name': 'Prince Edward Island', 'parent': 72, 'level': 3},
	'PEN': {'name': 'Pennsylvania', 'parent': 75, 'level': 3},
	'PER': {'name': 'Peru', 'parent': 83, 'level': 3},
	'PHI': {'name': 'Philippines', 'parent': 42, 'level': 3},
	'PHX': {'name': 'Phoenix Islands', 'parent': 60, 'level': 3},
	'PIT': {'name': 'Pitcairn Islands', 'parent': 61, 'level': 3},
	'POL': {'name': 'Poland', 'parent': 11, 'level': 3},
	'POR': {'name': 'Portugal', 'parent': 12, 'level': 3},
	'PRM': {'name': 'Primorye', 'parent': 31, 'level': 3},
	'PUE': {'name': 'Puerto Rico', 'parent': 81, 'level': 3},
	'QLD': {'name': 'Queensland', 'parent': 50, 'level': 3},
	'QUE': {'name': 'Québec', 'parent': 72, 'level': 3},
	'REU': {'name': 'Réunion', 'parent': 29, 'level': 3},
	'RHO': {'name': 'Rhode Island', 'parent': 75, 'level': 3},
	'ROD': {'name': 'Rodrigues', 'parent': 29, 'level': 3},
	'ROM': {'name': 'Romania', 'parent': 13, 'level': 3},
	'RUC': {'name': 'Central European Russia', 'parent': 14, 'level': 3},
	'RUE': {'name': 'East European Russia', 'parent': 14, 'level': 3},
	'RUN': {'name': 'North European Russia', 'parent': 14, 'level': 3},
	'RUS': {'name': 'South European Russia', 'parent': 14, 'level': 3},
	'RUW': {'name': 'Northwest European Russia', 'parent': 14, 'level': 3},
	'RWA': {'name': 'Rwanda', 'parent': 23, 'level': 3},
	'SAK': {'name': 'Sakhalin', 'parent': 31, 'level': 3},
	'SAM': {'name': 'Samoa', 'parent': 60, 'level': 3},
	'SAR': {'name': 'Sardegna', 'parent': 12, 'level': 3},
	'SAS': {'name': 'Saskatchewan', 'parent': 71, 'level': 3},
	'SAU': {'name': 'Saudi Arabia', 'parent': 35, 'level': 3},
	'SCA': {'name': 'South Carolina', 'parent': 78, 'level': 3},
	'SCI': {'name': 'Society Islands', 'parent': 61, 'level': 3},
	'SCS': {'name': 'South China Sea', 'parent': 41, 'level': 3},
	'SCZ': {'name': 'Santa Cruz Islands', 'parent': 60, 'level': 3},
	'SDA': {'name': 'South Dakota', 'parent': 74, 'level': 3},
	'SEL': {'name': 'Selvagens', 'parent': 21, 'level': 3},
	'SEN': {'name': 'Senegal', 'parent': 22, 'level': 3},
	'SEY': {'name': 'Seychelles', 'parent': 29, 'level': 3},
	'SGE': {'name': 'South Georgia', 'parent': 90, 'level': 3},
	'SIC': {'name': 'Sicilia', 'parent': 13, 'level': 3},
	'SIE': {'name': 'Sierra Leone', 'parent': 22, 'level': 3},
	'SIN': {'name': 'Sinai', 'parent': 34, 'level': 3},
	'SOA': {'name': 'South Australia', 'parent': 50, 'level': 3},
	'SOC': {'name': 'Socotra', 'parent': 24, 'level': 3},
	'SOL': {'name': 'Solomon Islands', 'parent': 43, 'level': 3},
	'SOM': {'name': 'Somalia', 'parent': 24, 'level': 3},
	'SPA': {'name': 'Spain', 'parent': 12, 'level': 3},
	'SRL': {'name': 'Sri Lanka', 'parent': 40, 'level': 3},
	'SSA': {'name': 'South Sandwich Islands', 'parent': 90, 'level': 3},
	'STH': {'name': 'St.Helena', 'parent': 28, 'level': 3},
	'SUD': {'name': 'Sudan', 'parent': 24, 'level': 3},
	'SUL': {'name': 'Sulawesi', 'parent': 42, 'level': 3},
	'SUM': {'name': 'Sumatera', 'parent': 42, 'level': 3},
	'SUR': {'name': 'Suriname', 'parent': 82, 'level': 3},
	'SVA': {'name': 'Svalbard', 'parent': 10, 'level': 3},
	'SWC': {'name': 'Southwest Caribbean', 'parent': 81, 'level': 3},
	'SWE': {'name': 'Sweden', 'parent': 10, 'level': 3},
	'SWI': {'name': 'Switzerland', 'parent': 11, 'level': 3},
	'SWZ': {'name': 'Swaziland', 'parent': 27, 'level': 3},
	'TAI': {'name': 'Taiwan', 'parent': 38, 'level': 3},
	'TAN': {'name': 'Tanzania', 'parent': 25, 'level': 3},
	'TAS': {'name': 'Tasmania', 'parent': 50, 'level': 3},
	'TCI': {'name': 'Turks-Caicos Islands', 'parent': 81, 'level': 3},
	'TCS': {'name': 'Transcaucasus', 'parent': 33, 'level': 3},
	'TDC': {'name': 'Tristan da Cunha', 'parent': 90, 'level': 3},
	'TEN': {'name': 'Tennessee', 'parent': 78, 'level': 3},
	'TEX': {'name': 'Texas', 'parent': 77, 'level': 3},
	'THA': {'name': 'Thailand', 'parent': 41, 'level': 3},
	'TKM': {'name': 'Turkmenistan', 'parent': 32, 'level': 3},
	'TOG': {'name': 'Togo', 'parent': 22, 'level': 3},
	'TOK': {'name': 'Tokelau-Manihiki', 'parent': 60, 'level': 3},
	'TON': {'name': 'Tonga', 'parent': 60, 'level': 3},
	'TRT': {'name': 'Trinidad-Tobago', 'parent': 81, 'level': 3},
	'TUA': {'name': 'Tuamotu', 'parent': 61, 'level': 3},
	'TUB': {'name': 'Tubuai Islands', 'parent': 61, 'level': 3},
	'TUE': {'name': 'European Turkey', 'parent': 13, 'level': 3},
	'TUN': {'name': 'Tunisia', 'parent': 20, 'level': 3},
	'TUR': {'name': 'Turkey', 'parent': 34, 'level': 3},
	'TUV': {'name': 'Tuvalu', 'parent': 60, 'level': 3},
	'TVA': {'name': 'Tuva', 'parent': 30, 'level': 3},
	'TVL': {'name': 'Northern Provinces', 'parent': 27, 'level': 3},
	'TZK': {'name': 'Tadzhikistan', 'parent': 32, 'level': 3},
	'UGA': {'name': 'Uganda', 'parent': 25, 'level': 3},
	'UKR': {'name': 'Ukraine', 'parent': 14, 'level': 3},
	'URU': {'name': 'Uruguay', 'parent': 85, 'level': 3},
	'UTA': {'name': 'Utah', 'parent': 76, 'level': 3},
	'UZB': {'name': 'Uzbekistan', 'parent': 32, 'level': 3},
	'VAN': {'name': 'Vanuatu', 'parent': 60, 'level': 3},
	'VEN': {'name': 'Venezuela', 'parent': 82, 'level': 3},
	'VER': {'name': 'Vermont', 'parent': 75, 'level': 3},
	'VIC': {'name': 'Victoria', 'parent': 50, 'level': 3},
	'VIE': {'name': 'Vietnam', 'parent': 41, 'level': 3},
	'VNA': {'name': 'Venezuelan Antilles', 'parent': 81, 'level': 3},
	'VRG': {'name': 'Virginia', 'parent': 78, 'level': 3},
	'WAK': {'name': 'Wake Island', 'parent': 62, 'level': 3},
	'WAL': {'name': 'Wallis-Futuna Islands', 'parent': 60, 'level': 3},
	'WAS': {'name': 'Washington', 'parent': 73, 'level': 3},
	'WAU': {'name': 'Western Australia', 'parent': 50, 'level': 3},
	'WDC': {'name': 'District of Columbia', 'parent': 78, 'level': 3},
	'WHM': {'name': 'West Himalaya', 'parent': 40, 'level': 3},
	'WIN': {'name': 'Windward Islands', 'parent': 81, 'level': 3},
	'WIS': {'name': 'Wisconsin', 'parent': 74, 'level': 3},
	'WSA': {'name': 'Western Sahara', 'parent': 20, 'level': 3},
	'WSB': {'name': 'West Siberia', 'parent': 30, 'level': 3},
	'WVA': {'name': 'West Virginia', 'parent': 75, 'level': 3},
	'WYO': {'name': 'Wyoming', 'parent': 73, 'level': 3},
	'XMS': {'name': 'Christmas Island', 'parent': 42, 'level': 3},
	'YAK': {'name': 'Yakutskiya', 'parent': 30, 'level': 3},
	'YEM': {'name': 'Yemen', 'parent': 35, 'level': 3},
	'YUG': {'name': 'Former Yugoslavia', 'parent': 13, 'level': 3},
	'YUK': {'name': 'Yukon', 'parent': 70, 'level': 3},
	'ZAI': {'name': 'DR Congo', 'parent': 23, 'level': 3},
	'ZAM': {'name': 'Zambia', 'parent': 26, 'level': 3},
	'ZIM': {'name': 'Zimbabwe', 'parent': 26, 'level': 3},
	# L4
	'AGE-BA': {'name': 'Buenos Aires', 'parent': 'AGE', 'level': 4},
	'AGE-CH': {'name': 'Chaco', 'parent': 'AGE', 'level': 4},
	'AGE-CN': {'name': 'Corrientes', 'parent': 'AGE', 'level': 4},
	'AGE-CO': {'name': 'Córdoba', 'parent': 'AGE', 'level': 4},
	'AGE-DF': {'name': 'Argentina Distrito Federal', 'parent': 'AGE', 'level': 4},
	'AGE-ER': {'name': 'Entre Ríos', 'parent': 'AGE', 'level': 4},
	'AGE-FO': {'name': 'Formosa', 'parent': 'AGE', 'level': 4},
	'AGE-LP': {'name': 'La Pampa', 'parent': 'AGE', 'level': 4},
	'AGE-MI': {'name': 'Misiones', 'parent': 'AGE', 'level': 4},
	'AGE-SF': {'name': 'Santa Fe', 'parent': 'AGS', 'level': 4},
	'AGS-CB': {'name': 'Chubut', 'parent': 'AGS', 'level': 4},
	'AGS-NE': {'name': 'Neuquén', 'parent': 'AGS', 'level': 4},
	'AGS-RN': {'name': 'Rio Negro', 'parent': 'AGS', 'level': 4},
	'AGS-SC': {'name': 'Santa Cruz', 'parent': 'AGS', 'level': 4},
	'AGS-TF': {'name': 'Tierra del Fuego (Argentina)', 'parent': 'AGS', 'level': 4},
	'AGW-CA': {'name': 'Catamarca', 'parent': 'AGW', 'level': 4},
	'AGW-JU': {'name': 'Jujuy', 'parent': 'AGW', 'level': 4},
	'AGW-LR': {'name': 'La Rioja', 'parent': 'AGW', 'level': 4},
	'AGW-ME': {'name': 'Mendoza', 'parent': 'AGW', 'level': 4},
	'AGW-SA': {'name': 'Salta', 'parent': 'AGW', 'level': 4},
	'AGW-SE': {'name': 'Santiago del Estero', 'parent': 'AGW', 'level': 4},
	'AGW-SJ': {'name': 'San Juan', 'parent': 'AGW', 'level': 4},
	'AGW-SL': {'name': 'San Luis', 'parent': 'AGW', 'level': 4},
	'AGW-TU': {'name': 'Tucuman', 'parent': 'AGW', 'level': 4},
	'AND-AN': {'name': 'Andaman Islands', 'parent': 'AND', 'level': 4},
	'AND-CO': {'name': 'Coco Islands', 'parent': 'AND', 'level': 4},
	'ASS-AS': {'name': 'Assam', 'parent': 'ASS', 'level': 4},
	'ASS-MA': {'name': 'Manipur', 'parent': 'ASS', 'level': 4},
	'ASS-ME': {'name': 'Meghalaya', 'parent': 'ASS', 'level': 4},
	'ASS-MI': {'name': 'Mizoram', 'parent': 'ASS', 'level': 4},
	'ASS-NA': {'name': 'Nagaland', 'parent': 'ASS', 'level': 4},
	'ASS-TR': {'name': 'Tripura', 'parent': 'ASS', 'level': 4},
	'AUT-AU': {'name': 'Austria', 'parent': 'AUT', 'level': 4},
	'AUT-LI': {'name': 'Liechtenstein', 'parent': 'AUT', 'level': 4},
	'BGM-BE': {'name': 'Belgium', 'parent': 'BGM', 'level': 4},
	'BGM-LU': {'name': 'Luxembourg', 'parent': 'BGM', 'level': 4},
	'BLT-ES': {'name': 'Estonia', 'parent': 'BLT', 'level': 4},
	'BLT-KA': {'name': 'Kaliningrad', 'parent': 'BLT', 'level': 4},
	'BLT-LA': {'name': 'Latvia', 'parent': 'BLT', 'level': 4},
	'BLT-LI': {'name': 'Lithuania', 'parent': 'BLT', 'level': 4},
	'BOR-BR': {'name': 'Brunei', 'parent': 'BOR', 'level': 4},
	'BOR-KA': {'name': 'Kalimantan', 'parent': 'BOR', 'level': 4},
	'BOR-SB': {'name': 'Sabah', 'parent': 'BOR', 'level': 4},
	'BOR-SR': {'name': 'Sarawak', 'parent': 'BOR', 'level': 4},
	'BZC-DF': {'name': 'Brazilia Distrito Federal', 'parent': 'BZC', 'level': 4},
	'BZC-GO': {'name': 'Goiás', 'parent': 'BZC', 'level': 4},
	'BZC-MS': {'name': 'Mato Grosso do Sul', 'parent': 'BZC', 'level': 4},
	'BZC-MT': {'name': 'Mato Grosso', 'parent': 'BZC', 'level': 4},
	'BZE-AL': {'name': 'Alagoas', 'parent': 'BZE', 'level': 4},
	'BZE-BA': {'name': 'Bahia', 'parent': 'BZE', 'level': 4},
	'BZE-CE': {'name': 'Ceará', 'parent': 'BZE', 'level': 4},
	'BZE-FN': {'name': 'Fernando de Noronha', 'parent': 'BZE', 'level': 4},
	'BZE-MA': {'name': 'Maranhao', 'parent': 'BZE', 'level': 4},
	'BZE-PB': {'name': 'Paraíba', 'parent': 'BZE', 'level': 4},
	'BZE-PE': {'name': 'Pernambuco', 'parent': 'BZE', 'level': 4},
	'BZE-PI': {'name': 'Piauí', 'parent': 'BZE', 'level': 4},
	'BZE-RN': {'name': 'Rio Grande do Norte', 'parent': 'BZE', 'level': 4},
	'BZE-SE': {'name': 'Sergipe', 'parent': 'BZE', 'level': 4},
	'BZL-ES': {'name': 'Espirito Santo', 'parent': 'BZL', 'level': 4},
	'BZL-MG': {'name': 'Minas Gerais', 'parent': 'BZL', 'level': 4},
	'BZL-RJ': {'name': 'Rio de Janeiro', 'parent': 'BZL', 'level': 4},
	'BZL-SP': {'name': 'São Paulo', 'parent': 'BZL', 'level': 4},
	'BZL-TR': {'name': 'Trindade', 'parent': 'BZL', 'level': 4},
	'BZN-AC': {'name': 'Acre', 'parent': 'BZN', 'level': 4},
	'BZN-AM': {'name': 'Amazonas', 'parent': 'BZN', 'level': 4},
	'BZN-AP': {'name': 'Amapá', 'parent': 'BZN', 'level': 4},
	'BZN-PA': {'name': 'Pará', 'parent': 'BZN', 'level': 4},
	'BZN-RM': {'name': 'Roraima', 'parent': 'BZN', 'level': 4},
	'BZN-RO': {'name': 'Rondônia', 'parent': 'BZN', 'level': 4},
	'BZN-TO': {'name': 'Tocantins', 'parent': 'BZN', 'level': 4},
	'BZS-PR': {'name': 'Paraná', 'parent': 'BZS', 'level': 4},
	'BZS-RS': {'name': 'Rio Grande do Sul', 'parent': 'BZS', 'level': 4},
	'BZS-SC': {'name': 'Santa Catarina', 'parent': 'BZS', 'level': 4},
	'CHC-GZ': {'name': 'Guizhou', 'parent': 'CHC', 'level': 4},
	'CHC-HU': {'name': 'Hubei', 'parent': 'CHC', 'level': 4},
	'CHC-SC': {'name': 'Sichuan', 'parent': 'CHC', 'level': 4},
	'CHC-YN': {'name': 'Yunnan', 'parent': 'CHC', 'level': 4},
	'CHC-CQ': {'name': 'Chongqing', 'parent': 'CHC', 'level': 4},
	'CHI-NM': {'name': 'Nei Mongol', 'parent': 'CHI', 'level': 4},
	'CHI-NX': {'name': 'Ningxia', 'parent': 'CHI', 'level': 4},
	'CHM-HJ': {'name': 'Heilongjiang', 'parent': 'CHM', 'level': 4},
	'CHM-JL': {'name': 'Jilin', 'parent': 'CHM', 'level': 4},
	'CHM-LN': {'name': 'Liaoning', 'parent': 'CHM', 'level': 4},
	'CHN-BJ': {'name': 'Beijing', 'parent': 'CHN', 'level': 4},
	'CHN-GS': {'name': 'Gansu', 'parent': 'CHN', 'level': 4},
	'CHN-HB': {'name': 'Hebei', 'parent': 'CHN', 'level': 4},
	'CHN-SA': {'name': 'Shaanxi', 'parent': 'CHN', 'level': 4},
	'CHN-SD': {'name': 'Shandong', 'parent': 'CHN', 'level': 4},
	'CHN-SX': {'name': 'Shanxi', 'parent': 'CHN', 'level': 4},
	'CHN-TJ': {'name': 'Tianjin', 'parent': 'CHN', 'level': 4},
	'CHS-AH': {'name': 'Anhui', 'parent': 'CHS', 'level': 4},
	'CHS-FJ': {'name': 'Fujian', 'parent': 'CHS', 'level': 4},
	'CHS-GD': {'name': 'Guangdong', 'parent': 'CHS', 'level': 4},
	'CHS-GX': {'name': 'Guangxi', 'parent': 'CHS', 'level': 4},
	'CHS-HE': {'name': 'Henan', 'parent': 'CHS', 'level': 4},
	'CHS-HK': {'name': 'Hong Kong', 'parent': 'CHS', 'level': 4},
	'CHS-HN': {'name': 'Hunan', 'parent': 'CHS', 'level': 4},
	'CHS-JS': {'name': 'Jiangsu', 'parent': 'CHS', 'level': 4},
	'CHS-JX': {'name': 'Jiangxi', 'parent': 'CHS', 'level': 4},
	'CHS-KI': {'name': 'Kin-Men', 'parent': 'CHS', 'level': 4},
	'CHS-MA': {'name': 'Macau', 'parent': 'CHS', 'level': 4},
	'CHS-MP': {'name': 'Ma-tsu-Pai-chüan', 'parent': 'CHS', 'level': 4},
	'CHS-SH': {'name': 'Shanghai', 'parent': 'CHS', 'level': 4},
	'CHS-ZJ': {'name': 'Zhejiang', 'parent': 'CHS', 'level': 4},
	'CLC-BI': {'name': 'Biobío', 'parent': 'CLC', 'level': 4},
	'CLC-CO': {'name': 'Coquimbo', 'parent': 'CLC', 'level': 4},
	'CLC-LA': {'name': 'La Araucania', 'parent': 'CLC', 'level': 4},
	'CLC-MA': {'name': 'Maule', 'parent': 'CLC', 'level': 4},
	'CLC-OH': {'name': "O'Higgins", 'parent': 'CLC', 'level': 4},
	'CLC-SA': {'name': 'Santiago', 'parent': 'CLC', 'level': 4},
	'CLC-VA': {'name': 'Valparaíso', 'parent': 'CLC', 'level': 4},
	'CLN-AN': {'name': 'Antofagasta', 'parent': 'CLN', 'level': 4},
	'CLN-AT': {'name': 'Atacama', 'parent': 'CLN', 'level': 4},
	'CLN-TA': {'name': 'Tarapaca', 'parent': 'CLN', 'level': 4},
	'CLS-AI': {'name': 'Aisén', 'parent': 'CLS', 'level': 4},
	'CLS-LL': {'name': 'Los Lagos', 'parent': 'CLS', 'level': 4},
	'CLS-MG': {'name': 'Magellanes', 'parent': 'CLS', 'level': 4},
	'COM-CO': {'name': 'Comoros', 'parent': 'COM', 'level': 4},
	'COM-MA': {'name': 'Mayotte', 'parent': 'COM', 'level': 4},
	'CPI-CL': {'name': 'Clipperton Island', 'parent': 'CPI', 'level': 4},
	'CPI-CO': {'name': 'Cocos Island', 'parent': 'CPI', 'level': 4},
	'CPI-MA': {'name': 'Malpelo Island', 'parent': 'CPI', 'level': 4},
	'CPP-EC': {'name': 'Eastern Cape Province', 'parent': 'CPP', 'level': 4},
	'CPP-NC': {'name': 'Northern Cape Province', 'parent': 'CPP', 'level': 4},
	'CPP-WC': {'name': 'Western Cape Province', 'parent': 'CPP', 'level': 4},
	'CRL-MF': {'name': 'Micronesia Federated States', 'parent': 'CRL', 'level': 4},
	'CRL-PA': {'name': 'Palau', 'parent': 'CRL', 'level': 4},
	'CZE-CZ': {'name': 'Czech Republic', 'parent': 'CZE', 'level': 4},
	'CZE-SL': {'name': 'Slovakia', 'parent': 'CZE', 'level': 4},
	'EHM-AP': {'name': 'Arunachal Pradesh', 'parent': 'EHM', 'level': 4},
	'EHM-BH': {'name': 'Bhutan', 'parent': 'EHM', 'level': 4},
	'EHM-DJ': {'name': 'Darjiling', 'parent': 'EHM', 'level': 4},
	'EHM-SI': {'name': 'Sikkim', 'parent': 'EHM', 'level': 4},
	'FRA-CI': {'name': 'Channel Islands', 'parent': 'FRA', 'level': 4},
	'FRA-FR': {'name': 'France', 'parent': 'FRA', 'level': 4},
	'FRA-MO': {'name': 'Monaco', 'parent': 'FRA', 'level': 4},
	'GGI-AN': {'name': 'Annobón', 'parent': 'GGI', 'level': 4},
	'GGI-BI': {'name': 'Bioko', 'parent': 'GGI', 'level': 4},
	'GGI-PR': {'name': 'Principe', 'parent': 'GGI', 'level': 4},
	'GGI-ST': {'name': 'São Tomé', 'parent': 'GGI', 'level': 4},
	'GST-BA': {'name': 'Bahrain', 'parent': 'GST', 'level': 4},
	'GST-QA': {'name': 'Qatar', 'parent': 'GST', 'level': 4},
	'GST-UA': {'name': 'United Arab Emirates', 'parent': 'GST', 'level': 4},
	'HAI-HA': {'name': 'Haiti', 'parent': 'HAI', 'level': 4},
	'HAI-NI': {'name': 'Navassa Island', 'parent': 'HAI', 'level': 4},
	'HAW-HI': {'name': 'Hawaiian Islands', 'parent': 'HAW', 'level': 4},
	'HAW-JI': {'name': 'Johnston Island', 'parent': 'HAW', 'level': 4},
	'HAW-MI': {'name': 'Midway Islands', 'parent': 'HAW', 'level': 4},
	'IND-AP': {'name': 'Andhra Pradesh', 'parent': 'IND', 'level': 4},
	'IND-BI': {'name': 'Bihar', 'parent': 'IND', 'level': 4},
	'IND-CH': {'name': 'Chandigarh', 'parent': 'IND', 'level': 4},
	'IND-DD': {'name': 'Dadra-Nagar-Haveli', 'parent': 'IND', 'level': 4},
	'IND-DE': {'name': 'Delhi', 'parent': 'IND', 'level': 4},
	'IND-DI': {'name': 'Diu', 'parent': 'IND', 'level': 4},
	'IND-DM': {'name': 'Daman', 'parent': 'IND', 'level': 4},
	'IND-GO': {'name': 'Goa', 'parent': 'IND', 'level': 4},
	'IND-GU': {'name': 'Gujarat', 'parent': 'IND', 'level': 4},
	'IND-HA': {'name': 'Haryana', 'parent': 'IND', 'level': 4},
	'IND-KE': {'name': 'Kerala', 'parent': 'IND', 'level': 4},
	'IND-KL': {'name': 'Karaikal', 'parent': 'IND', 'level': 4},
	'IND-KT': {'name': 'Karnataka', 'parent': 'IND', 'level': 4},
	'IND-MH': {'name': 'Mahé', 'parent': 'IND', 'level': 4},
	'IND-MP': {'name': 'Madhya Pradesh', 'parent': 'IND', 'level': 4},
	'IND-MR': {'name': 'Maharashtra', 'parent': 'IND', 'level': 4},
	'IND-OR': {'name': 'Orissa', 'parent': 'IND', 'level': 4},
	'IND-PO': {'name': 'Pondicherry', 'parent': 'IND', 'level': 4},
	'IND-PU': {'name': 'Punjab', 'parent': 'IND', 'level': 4},
	'IND-RA': {'name': 'Rajasthan', 'parent': 'IND', 'level': 4},
	'IND-TN': {'name': 'Tamil Nadu', 'parent': 'IND', 'level': 4},
	'IND-UP': {'name': 'Uttar Pradesh', 'parent': 'IND', 'level': 4},
	'IND-WB': {'name': 'West Bengal', 'parent': 'IND', 'level': 4},
	'IND-YA': {'name': 'Yanam', 'parent': 'IND', 'level': 4},
	'IND-JK': {'name': 'Jharkhand', 'parent': 'IND', 'level': 4},
	'IND-CT': {'name': 'Chattisgarh', 'parent': 'IND', 'level': 4},
	'IRE-IR': {'name': 'Ireland', 'parent': 'IRE', 'level': 4},
	'IRE-NI': {'name': 'Northern Ireland', 'parent': 'IRE', 'level': 4},
	'ITA-IT': {'name': 'Italy', 'parent': 'ITA', 'level': 4},
	'ITA-SM': {'name': 'San Marino', 'parent': 'ITA', 'level': 4},
	'ITA-VC': {'name': 'Vatican City', 'parent': 'ITA', 'level': 4},
	'JAP-HK': {'name': 'Hokkaido', 'parent': 'JAP', 'level': 4},
	'JAP-HN': {'name': 'Honshu', 'parent': 'JAP', 'level': 4},
	'JAP-KY': {'name': 'Kyushu', 'parent': 'JAP', 'level': 4},
	'JAP-SH': {'name': 'Shikoku', 'parent': 'JAP', 'level': 4},
	'KOR-NK': {'name': 'North Korea', 'parent': 'KOR', 'level': 4},
	'KOR-SK': {'name': 'South Korea', 'parent': 'KOR', 'level': 4},
	'LBS-LB': {'name': 'Lebanon', 'parent': 'LBS', 'level': 4},
	'LBS-SY': {'name': 'Syria', 'parent': 'LBS', 'level': 4},
	'LEE-AB': {'name': 'Antigua-Barbuda', 'parent': 'LEE', 'level': 4},
	'LEE-AG': {'name': 'Anguilla', 'parent': 'LEE', 'level': 4},
	'LEE-AV': {'name': 'Aves Island', 'parent': 'LEE', 'level': 4},
	'LEE-BV': {'name': 'British Virgin Islands', 'parent': 'LEE', 'level': 4},
	'LEE-GU': {'name': 'Guadeloupe', 'parent': 'LEE', 'level': 4},
	'LEE-MO': {'name': 'Montserrat', 'parent': 'LEE', 'level': 4},
	'LEE-NL': {'name': 'Leeward Islands', 'parent': 'LEE', 'level': 4},
	'LEE-SK': {'name': 'St.Kitts-Nevis', 'parent': 'LEE', 'level': 4},
	'LEE-SM': {'name': 'St. Martin-St. Barthélemy', 'parent': 'LEE', 'level': 4},
	'LEE-VI': {'name': 'Virgin Islands', 'parent': 'LEE', 'level': 4},
	'LIN-KI': {'name': 'Kiribati Line Islands', 'parent': 'LIN', 'level': 4},
	'LIN-US': {'name': 'U.S. Line Islands', 'parent': 'LIN', 'level': 4},
	'LSI-BA': {'name': 'Bali', 'parent': 'LSI', 'level': 4},
	'LSI-ET': {'name': 'Timor-Leste', 'parent': 'LSI', 'level': 4},
	'LSI-LS': {'name': 'Lesser Sunda Islands', 'parent': 'LSI', 'level': 4},
	'MLY-PM': {'name': 'Peninsular Malaysia', 'parent': 'MLY', 'level': 4},
	'MLY-SI': {'name': 'Singapore', 'parent': 'MLY', 'level': 4},
	'MOR-MO': {'name': 'Morocco', 'parent': 'MOR', 'level': 4},
	'MOR-SP': {'name': 'Ceuta and Melilla', 'parent': 'MOR', 'level': 4},
	'MRN-GU': {'name': 'Guam', 'parent': 'MRN', 'level': 4},
	'MRN-NM': {'name': 'Northern Marianas', 'parent': 'MRN', 'level': 4},
	'MXC-DF': {'name': 'Mexico Distrito Federal', 'parent': 'MXC', 'level': 4},
	'MXC-ME': {'name': 'México State', 'parent': 'MXC', 'level': 4},
	'MXC-MO': {'name': 'Morelos', 'parent': 'MXC', 'level': 4},
	'MXC-PU': {'name': 'Puebla', 'parent': 'MXC', 'level': 4},
	'MXC-TL': {'name': 'Tlaxcala', 'parent': 'MXC', 'level': 4},
	'MXE-AG': {'name': 'Aguascalientes', 'parent': 'MXE', 'level': 4},
	'MXE-CO': {'name': 'Coahuila', 'parent': 'MXE', 'level': 4},
	'MXE-CU': {'name': 'Chihuahua', 'parent': 'MXE', 'level': 4},
	'MXE-DU': {'name': 'Durango', 'parent': 'MXE', 'level': 4},
	'MXE-GU': {'name': 'Guanajuato', 'parent': 'MXE', 'level': 4},
	'MXE-HI': {'name': 'Hidalgo', 'parent': 'MXE', 'level': 4},
	'MXE-NL': {'name': 'Nuevo León', 'parent': 'MXE', 'level': 4},
	'MXE-QU': {'name': 'Querétaro', 'parent': 'MXE', 'level': 4},
	'MXE-SL': {'name': 'San Luis Potosí', 'parent': 'MXE', 'level': 4},
	'MXE-TA': {'name': 'Tamaulipas', 'parent': 'MXE', 'level': 4},
	'MXE-ZA': {'name': 'Zacatecas', 'parent': 'MXE', 'level': 4},
	'MXG-VC': {'name': 'Veracruz', 'parent': 'MXG', 'level': 4},
	'MXI-GU': {'name': 'Guadalupe Island', 'parent': 'MXI', 'level': 4},
	'MXI-RA': {'name': 'Rocas Alijos', 'parent': 'MXI', 'level': 4},
	'MXI-RG': {'name': 'Revillagigedo Islands', 'parent': 'MXI', 'level': 4},
	'MXN-BC': {'name': 'Baja California', 'parent': 'MXN', 'level': 4},
	'MXN-BS': {'name': 'Baja California Sur', 'parent': 'MXN', 'level': 4},
	'MXN-SI': {'name': 'Sinaloa', 'parent': 'MXN', 'level': 4},
	'MXN-SO': {'name': 'Sonora', 'parent': 'MXN', 'level': 4},
	'MXS-CL': {'name': 'Colima', 'parent': 'MXS', 'level': 4},
	'MXS-GR': {'name': 'Guerrero', 'parent': 'MXS', 'level': 4},
	'MXS-JA': {'name': 'Jalisco', 'parent': 'MXS', 'level': 4},
	'MXS-MI': {'name': 'Michoacán', 'parent': 'MXS', 'level': 4},
	'MXS-NA': {'name': 'Nayarit', 'parent': 'MXS', 'level': 4},
	'MXS-OA': {'name': 'Oaxaca', 'parent': 'MXS', 'level': 4},
	'MXT-CA': {'name': 'Campeche', 'parent': 'MXT', 'level': 4},
	'MXT-CI': {'name': 'Chiapas', 'parent': 'MXT', 'level': 4},
	'MXT-QR': {'name': 'Quintana Roo', 'parent': 'MXT', 'level': 4},
	'MXT-TB': {'name': 'Tabasco', 'parent': 'MXT', 'level': 4},
	'MXT-YU': {'name': 'Yucatán', 'parent': 'MXT', 'level': 4},
	'NCS-DA': {'name': 'Dagestan', 'parent': 'NCS', 'level': 4},
	'NCS-KB': {'name': 'Kabardino-Balkariya', 'parent': 'NCS', 'level': 4},
	'NCS-KC': {'name': 'Karacheyevo-Cherkessiya', 'parent': 'NCS', 'level': 4},
	'NCS-KR': {'name': 'Krasnodar', 'parent': 'NCS', 'level': 4},
	'NCS-SO': {'name': 'Severo-Osetiya', 'parent': 'NCS', 'level': 4},
	'NCS-ST': {'name': 'Stavropol', 'parent': 'NCS', 'level': 4},
	'NCS-CH': {'name': 'Chechnya', 'parent': 'NCS', 'level': 4},
	'NCS-IN': {'name': 'Ingushetiya', 'parent': 'NCS', 'level': 4},
	'NFK-LH': {'name': 'Lord Howe Island', 'parent': 'NFK', 'level': 4},
	'NFK-NI': {'name': 'Norfolk Island', 'parent': 'NFK', 'level': 4},
	'NFL-NE': {'name': 'Newfoundland', 'parent': 'NFL', 'level': 4},
	'NFL-SP': {'name': 'St.Pierre-Miquelon', 'parent': 'NFL', 'level': 4},
	'NLA-BO': {'name': 'Bonaire', 'parent': 'NLA', 'level': 4},
	'NLA-CU': {'name': 'Curaçao', 'parent': 'NLA', 'level': 4},
	'NSW-CT': {'name': 'Australian Capital Territory', 'parent': 'NSW', 'level': 4},
	'NSW-NS': {'name': 'New South Wales', 'parent': 'NSW', 'level': 4},
	'NWG-IJ': {'name': 'Irian Jaya', 'parent': 'NWG', 'level': 4},
	'NWG-PN': {'name': 'Papua New Guinea', 'parent': 'NWG', 'level': 4},
	'PAL-IS': {'name': 'Israel', 'parent': 'PAL', 'level': 4},
	'PAL-JO': {'name': 'Jordan', 'parent': 'PAL', 'level': 4},
	'QLD-CS': {'name': 'Coral Sea Islands Territory', 'parent': 'QLD', 'level': 4},
	'QLD-QU': {'name': 'Queensland', 'parent': 'QLD', 'level': 4},
	'SAM-AS': {'name': 'American Samoa', 'parent': 'SAM', 'level': 4},
	'SAM-WS': {'name': 'Samoa', 'parent': 'SAM', 'level': 4},
	'SCS-PI': {'name': 'Paracel Islands', 'parent': 'SCS', 'level': 4},
	'SCS-SI': {'name': 'Spratly Islands', 'parent': 'SCS', 'level': 4},
	'SIC-MA': {'name': 'Malta', 'parent': 'SIC', 'level': 4},
	'SIC-SI': {'name': 'Sicilia', 'parent': 'SIC', 'level': 4},
	'SOL-NO': {'name': 'North Solomons', 'parent': 'SOL', 'level': 4},
	'SOL-SO': {'name': 'South Solomons', 'parent': 'SOL', 'level': 4},
	'SPA-AN': {'name': 'Andorra', 'parent': 'SPA', 'level': 4},
	'SPA-GI': {'name': 'Gibraltar', 'parent': 'SPA', 'level': 4},
	'SPA-SP': {'name': 'Spain', 'parent': 'SPA', 'level': 4},
	'SWC-CC': {'name': 'Colombian Caribbean Islands', 'parent': 'SWC', 'level': 4},
	'SWC-HC': {'name': 'Honduran Caribbean Islands', 'parent': 'SWC', 'level': 4},
	'SWC-NC': {'name': 'Nicaraguan Caribbean Islands', 'parent': 'SWC', 'level': 4},
	'TCS-AB': {'name': 'Abkhaziya', 'parent': 'TCS', 'level': 4},
	'TCS-AD': {'name': 'Adzhariya', 'parent': 'TCS', 'level': 4},
	'TCS-AR': {'name': 'Armenia', 'parent': 'TCS', 'level': 4},
	'TCS-AZ': {'name': 'Azerbaijan', 'parent': 'TCS', 'level': 4},
	'TCS-GR': {'name': 'Georgia', 'parent': 'TCS', 'level': 4},
	'TCS-NA': {'name': 'Nakhichevan', 'parent': 'TCS', 'level': 4},
	'TCS-NK': {'name': 'Nagorno Karabakh', 'parent': 'TCS', 'level': 4},
	'TOK-MA': {'name': 'Manihiki Islands', 'parent': 'TOK', 'level': 4},
	'TOK-SW': {'name': 'Swains Island', 'parent': 'TOK', 'level': 4},
	'TOK-TO': {'name': 'Tokelau', 'parent': 'TOK', 'level': 4},
	'TVL-GA': {'name': 'Gauteng', 'parent': 'TVL', 'level': 4},
	'TVL-MP': {'name': 'Mpumalanga', 'parent': 'TVL', 'level': 4},
	'TVL-NP': {'name': 'Northern Province', 'parent': 'TVL', 'level': 4},
	'TVL-NW': {'name': 'North-West Province', 'parent': 'TVL', 'level': 4},
	'UKR-MO': {'name': 'Moldova', 'parent': 'UKR', 'level': 4},
	'UKR-UK': {'name': 'Ukraine', 'parent': 'UKR', 'level': 4},
	'WAU-AC': {'name': 'Ashmore-Cartier Islands', 'parent': 'WAU', 'level': 4},
	'WAU-WA': {'name': 'Western Australia', 'parent': 'WAU', 'level': 4},
	'WHM-HP': {'name': 'Himachal Pradesh', 'parent': 'WHM', 'level': 4},
	'WHM-JK': {'name': 'Jammu-Kashmir', 'parent': 'WHM', 'level': 4},
	'WHM-UT': {'name': 'Uttaranchal', 'parent': 'WHM', 'level': 4},
	'WIN-BA': {'name': 'Barbados', 'parent': 'WIN', 'level': 4},
	'WIN-DO': {'name': 'Dominica', 'parent': 'WIN', 'level': 4},
	'WIN-GR': {'name': 'Grenada', 'parent': 'WIN', 'level': 4},
	'WIN-MA': {'name': 'Martinique', 'parent': 'WIN', 'level': 4},
	'WIN-SL': {'name': 'St.Lucia', 'parent': 'WIN', 'level': 4},
	'WIN-SV': {'name': 'St.Vincent', 'parent': 'WIN', 'level': 4},
	'YEM-NY': {'name': 'Yemen (North)', 'parent': 'YEM', 'level': 4},
	'YEM-SY': {'name': 'Yemen (South)', 'parent': 'YEM', 'level': 4},
	'YUG-BH': {'name': 'Bosnia and Herzegovina', 'parent': 'YUG', 'level': 4},
	'YUG-CR': {'name': 'Croatia', 'parent': 'YUG', 'level': 4},
	'YUG-KO': {'name': 'Kosovo', 'parent': 'YUG', 'level': 4},
	'YUG-MA': {'name': 'North Macedonia', 'parent': 'YUG', 'level': 4},
	'YUG-MN': {'name': 'Montenegro', 'parent': 'YUG', 'level': 4},
	'YUG-SE': {'name': 'Serbia', 'parent': 'YUG', 'level': 4},
	'YUG-SL': {'name': 'Slovenia', 'parent': 'YUG', 'level': 4}
}